In [10]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
import seaborn as sns
import statsmodels.api as sm
from sklearn import linear_model

In [11]:
# Reading in the .csv file
df = pd.read_csv('final_project.csv', index_col=0)
df.head(20)

,Expenditure,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Total National Health Expenditures,"2,023,744","2,156,158",2295307.0,2399121.0,2495414.0,2598823.0,2689349.0,2797260.0,2879008.0,3026157.0,3200815.0,3337248.0
1,Out of pocket,"263,815","273,254",290000.0,295184.0,293723.0,299742.0,309973.0,318330.0,325189.0,330068.0,339315.0,352537.0
2,Health Insurance,"1,414,078","1,517,387",1609250.0,1695968.0,1796424.0,1876922.0,1950187.0,2022904.0,2087804.0,2228136.0,2382770.0,2486842.0
3,Private Health Insurance,"701,176","737,122",776176.0,802857.0,832906.0,864344.0,898631.0,928211.0,946398.0,999940.0,1068778.0,1123372.0
4,Medicare,"339,762","403,690",432751.0,466971.0,498859.0,519787.0,544679.0,569634.0,590163.0,618889.0,648808.0,672093.0
5,Medicaid (Title XIX),"309,275","306,584",325746.0,344214.0,374421.0,397226.0,406744.0,422688.0,445361.0,496645.0,544073.0,565550.0
6,Federal,"177,461","173,879",185485.0,203084.0,247326.0,266360.0,247125.0,243251.0,256907.0,305106.0,343123.0,358095.0
7,State and Local,"131,814","132,705",140261.0,141129.0,127094.0,130865.0,159619.0,179438.0,188454.0,191540.0,200951.0,207454.0
8,CHIP (Title XIX and Title XXI),"7,566","8,366",9117.0,10210.0,11106.0,11540.0,11990.0,12629.0,13509.0,13215.0,14853.0,16883.0

In [15]:
#df.2005 = df.2005.str.replace(' -   ', '0')
df['2005'] = df['2005'].str.replace(',', '')
df['2005'] = df['2005'].astype(float)

In [16]:
df['2006'] = df['2006'].str.replace(',', '')
df['2006'] = df['2006'].astype(float)

In [18]:
df.head(20)

,Expenditure,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Total National Health Expenditures,2023744.0,2156158.0,2295307.0,2399121.0,2495414.0,2598823.0,2689349.0,2797260.0,2879008.0,3026157.0,3200815.0,3337248.0
1,Out of pocket,263815.0,273254.0,290000.0,295184.0,293723.0,299742.0,309973.0,318330.0,325189.0,330068.0,339315.0,352537.0
2,Health Insurance,1414078.0,1517387.0,1609250.0,1695968.0,1796424.0,1876922.0,1950187.0,2022904.0,2087804.0,2228136.0,2382770.0,2486842.0
3,Private Health Insurance,701176.0,737122.0,776176.0,802857.0,832906.0,864344.0,898631.0,928211.0,946398.0,999940.0,1068778.0,1123372.0
4,Medicare,339762.0,403690.0,432751.0,466971.0,498859.0,519787.0,544679.0,569634.0,590163.0,618889.0,648808.0,672093.0
5,Medicaid (Title XIX),309275.0,306584.0,325746.0,344214.0,374421.0,397226.0,406744.0,422688.0,445361.0,496645.0,544073.0,565550.0
6,Federal,177461.0,173879.0,185485.0,203084.0,247326.0,266360.0,247125.0,243251.0,256907.0,305106.0,343123.0,358095.0
7,State and Local,131814.0,132705.0,140261.0,141129.0,127094.0,130865.0,159619.0,179438.0,188454.0,191540.0,200951.0,207454.0
8,CHIP (Title XIX and Title XXI),7566.0,8366.0,9117.0,10210.0,11106.0,11540.0,11990.0,12629.0,13509.0,13215.0,14853.0,16883.0

In [19]:
df.drop(df.index[[3,4,5,8]])

,Expenditure,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Total National Health Expenditures,2023744.0,2156158.0,2295307.0,2399121.0,2495414.0,2598823.0,2689349.0,2797260.0,2879008.0,3026157.0,3200815.0,3337248.0
1,Out of pocket,263815.0,273254.0,290000.0,295184.0,293723.0,299742.0,309973.0,318330.0,325189.0,330068.0,339315.0,352537.0
2,Health Insurance,1414078.0,1517387.0,1609250.0,1695968.0,1796424.0,1876922.0,1950187.0,2022904.0,2087804.0,2228136.0,2382770.0,2486842.0
6,Federal,177461.0,173879.0,185485.0,203084.0,247326.0,266360.0,247125.0,243251.0,256907.0,305106.0,343123.0,358095.0
7,State and Local,131814.0,132705.0,140261.0,141129.0,127094.0,130865.0,159619.0,179438.0,188454.0,191540.0,200951.0,207454.0

In [20]:
df.drop('2005', axis = 1)

,Expenditure,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Total National Health Expenditures,2156158.0,2295307.0,2399121.0,2495414.0,2598823.0,2689349.0,2797260.0,2879008.0,3026157.0,3200815.0,3337248.0
1,Out of pocket,273254.0,290000.0,295184.0,293723.0,299742.0,309973.0,318330.0,325189.0,330068.0,339315.0,352537.0
2,Health Insurance,1517387.0,1609250.0,1695968.0,1796424.0,1876922.0,1950187.0,2022904.0,2087804.0,2228136.0,2382770.0,2486842.0
3,Private Health Insurance,737122.0,776176.0,802857.0,832906.0,864344.0,898631.0,928211.0,946398.0,999940.0,1068778.0,1123372.0
4,Medicare,403690.0,432751.0,466971.0,498859.0,519787.0,544679.0,569634.0,590163.0,618889.0,648808.0,672093.0
5,Medicaid (Title XIX),306584.0,325746.0,344214.0,374421.0,397226.0,406744.0,422688.0,445361.0,496645.0,544073.0,565550.0
6,Federal,173879.0,185485.0,203084.0,247326.0,266360.0,247125.0,243251.0,256907.0,305106.0,343123.0,358095.0
7,State and Local,132705.0,140261.0,141129.0,127094.0,130865.0,159619.0,179438.0,188454.0,191540.0,200951.0,207454.0
8,CHIP (Title XIX and Title XXI),8366.0,9117.0,10210.0,11106.0,11540.0,11990.0,12629.0,13509.0,13215.0,14853.0,16883.0

In [ ]:
df.to_csv('final_project_v2.csv')